defaults:
  - base_training

learning_rate: 0.0001
epochs: 5
loss: loss
loss_name: mse
num_classes: 5

W_loss_ce: 1.0
W_match_ce: 1.0
W_loss_bbox: 5.0
W_match_bbox: 5.0
W_loss_giou: 2.0
W_match_giou: 2.0
W_loss_motion: 1.0